"""Stream schemas for tap-stripe."""

from singer_sdk.typing import (
    IntegerType,
    StringType,
    DateTimeType,
    ObjectType,
    Property,
    PropertiesList,
    ArrayType,
    BooleanType,
    NumberType,
)

charges_schema = PropertiesList(
    Property("id", StringType),
    Property("amount", IntegerType),
    Property("amount_captured", IntegerType),
    Property("amount_refunded", IntegerType),
    Property("application", StringType),
    Property("application_fee", StringType),
    Property("application_fee_amount", IntegerType),
    Property("balance_transaction", StringType),
    Property(
        "billing_details",
        ObjectType(
            Property(
                "address",
                ObjectType(
                    Property("city", StringType),
                    Property("country", StringType),
                    Property("line1", StringType),
                    Property("line2", StringType),
                    Property("postal_code", StringType),
                    Property("state", StringType),
                ),
            ),
            Property("email", StringType),
            Property("name", StringType),
            Property("phone", StringType),
        ),
    ),
    Property("calculated_statement_descriptor", StringType),
    Property("captured", BooleanType),
    Property("created", IntegerType),
    Property("currency", StringType),
    Property("customer", StringType),
    Property("description", StringType),
    Property("disputed", BooleanType),
    Property("failure_balance_transaction", StringType),
    Property("failure_code", StringType),
    Property("failure_message", StringType),
    Property(
        "fraud_details",
        ObjectType(
            Property("stripe_report", StringType),
            Property("user_report", StringType),
        ),
    ),
    Property("invoice", StringType),
    Property("livemode", BooleanType),
    Property(
        "metadata",
        ObjectType(
            Property("customerId", StringType),
            Property("fingerprint", StringType),
            Property("paymentFlowId", StringType),
            Property("isForPayoutReversal", StringType),
            Property("manuallyFixedByTeamDelta", StringType),
            Property("paymentId", StringType),
        ),
    ),
    Property("on_behalf_of", StringType),
    Property(
        "outcome",
        ObjectType(
            Property("network_status", StringType),
            Property("reason", StringType),
            Property("risk_level", StringType),
            Property("risk_score", IntegerType),
            Property("rule", StringType),
            Property("seller_message", StringType),
            Property("type", StringType),
        ),
    ),
    Property("paid", BooleanType),
    Property("payment_intent", StringType),
    Property("payment_method", StringType),
    Property("payment_method_details", ObjectType()),
    Property("receipt_email", StringType),
    Property("receipt_number", StringType),
    Property("receipt_url", StringType),
    Property("refunded", BooleanType),
    Property("review", StringType),
    Property("source_transfer", StringType),
    Property("statement_descriptor", StringType),
    Property("statement_descriptor_suffix", StringType),
    Property("status", StringType),
    Property(
        "transfer_data",
        ObjectType(
            Property("amount", StringType),
            Property("destination", StringType),
        ),
    ),
    Property("transfer_group", StringType),
).to_dict()


disputes_schema = PropertiesList(
    Property("id", StringType),
    Property("object", StringType),
    Property("amount", IntegerType),
    Property(
        "balance_transactions",
        ArrayType(
            Property("id", StringType),
        ),
    ),
    Property("charge", StringType),
    Property("created", IntegerType),
    Property("currency", StringType),
    Property(
        "evidence",
        ObjectType(
            Property("access_activity_log", StringType),
            Property("billing_address", StringType),
            Property("cancellation_policy", StringType),
            Property("cancellation_policy_disclosure", StringType),
            Property("cancellation_rebuttal", StringType),
            Property("customer_communication", StringType),
            Property("customer_email_address", StringType),
            Property("customer_name", StringType),
            Property("customer_purchase_ip", StringType),
            Property("customer_signature", StringType),
            Property("duplicate_charge_documentation", StringType),
            Property("duplicate_charge_explanation", StringType),
            Property("duplicate_charge_id", StringType),
            Property("receipt", StringType),
            Property("refund_policy", StringType),
            Property("refund_policy_disclosure", StringType),
            Property("refund_refusal_explanation", StringType),
            Property("service_date", StringType),
            Property("service_documentation", StringType),
            Property("shipping_address", StringType),
            Property("shipping_carrier", StringType),
            Property("shipping_date", StringType),
            Property("shipping_documentation", StringType),
            Property("shipping_tracking_number", StringType),
            Property("uncategorized_file", StringType),
            Property("uncategorized_text", StringType),
        ),
    ),
    Property(
        "evidence_details",
        ObjectType(
            Property("due_by", IntegerType),
            Property("has_evidence", BooleanType),
            Property("past_due", BooleanType),
            Property("submission_count", IntegerType),
        ),
    ),
    Property("is_charge_refundable", BooleanType),
    Property("livemode", BooleanType),
    Property("metadata", ObjectType()),
    Property("payment_intent", StringType),
    Property("reason", StringType),
    Property("status", StringType),
).to_dict()


exchange_rates_schema = PropertiesList(
    Property("send_currency", StringType),
    Property("receive_currency", StringType),
    Property("rate", NumberType),
    Property("date", DateTimeType),
).to_dict()


report_runs_schema = PropertiesList(
    Property("id", StringType),
    Property("object", StringType),
    Property("created", IntegerType),
    Property("error", StringType),
    Property("livemode", BooleanType),
    Property("parameters", ObjectType(Property("interval_end", IntegerType), Property("interval_start", IntegerType))),
    Property("report_type", StringType),
    Property(
        "result",
        ObjectType(
            Property("id", StringType),
            Property("object", StringType),
            Property("created", IntegerType),
            Property("expires_at", IntegerType),
            Property("filename", StringType),
            Property(
                "links",
                ObjectType(
                    Property("object", StringType),
                    Property("data", ArrayType(ObjectType(Property("id", StringType)))),
                    Property("has_more", BooleanType),
                    Property("url", StringType),
                ),
            ),
            Property("purpose", StringType),
            Property("size", IntegerType),
            Property("title", StringType),
            Property("type", StringType),
            Property("url", StringType),
        ),
    ),
    Property("status", StringType),
    Property("succeeded_at", IntegerType),
).to_dict()


activity_itemized_2_schema = PropertiesList(
    Property("balance_transaction_id", StringType),
    Property("balance_transaction_created_at", DateTimeType),
    Property("balance_transaction_reporting_category", StringType),
    Property("balance_transaction_component", StringType),
    Property("balance_transaction_regulatory_tag", StringType),
    Property("activity_at", DateTimeType),
    Property("currency", StringType),
    Property("amount", NumberType),
    Property("charge_id", StringType),
    Property("payment_intent_id", StringType),
    Property("refund_id", StringType),
    Property("dispute_id", StringType),
    Property("invoice_id", StringType),
    Property("invoice_number", StringType),
    Property("subscription_id", StringType),
    Property("fee_id", StringType),
    Property("transfer_id", StringType),
    Property("destination_id", StringType),
    Property("customer_id", StringType),
    Property("customer_email", StringType),
    Property("customer_description", StringType),
    Property("customer_shipping_address_line1", StringType),
    Property("customer_shipping_address_line2", StringType),
    Property("customer_shipping_address_city", StringType),
    Property("customer_shipping_address_state", StringType),
    Property("customer_shipping_address_postal_code", StringType),
    Property("customer_shipping_address_country", StringType),
    Property("customer_address_line1", StringType),
    Property("customer_address_line2", StringType),
    Property("customer_address_city", StringType),
    Property("customer_address_state", StringType),
    Property("customer_address_postal_code", StringType),
    Property("customer_address_country", StringType),
    Property("shipping_address_line1", StringType),
    Property("shipping_address_line2", StringType),
    Property("shipping_address_city", StringType),
    Property("shipping_address_state", StringType),
    Property("shipping_address_postal_code", StringType),
    Property("shipping_address_country", StringType),
    Property("card_address_line1", StringType),
    Property("card_address_line2", StringType),
    Property("card_address_city", StringType),
    Property("card_address_state", StringType),
    Property("card_address_postal_code", StringType),
    Property("card_address_country", StringType),
    Property("automatic_payout_id", StringType),
    Property("automatic_payout_effective_at", DateTimeType),
    Property("event_type", StringType),
    Property("payment_method_type", StringType),
    Property("is_link", BooleanType),
    Property("card_brand", StringType),
    Property("card_funding", StringType),
    Property("card_country", IntegerType),
    Property("statement_descriptor", StringType),
    Property("customer_facing_currency", StringType),
    Property("customer_facing_amount", NumberType),
    Property("activity_interval_type", StringType),
    Property("activity_start_date", DateTimeType),
    Property("activity_end_date", DateTimeType),
    Property("balance_transaction_description", StringType),
    Property("connected_account_id", StringType),
    Property("connected_account_name", StringType),
    Property("connected_account_country", StringType),
    Property("connected_account_direct_charge_id", StringType),
    Property("interval_end_at", IntegerType),
    Property("loaded_at", DateTimeType),
).to_dict()


activity_summary_1_schema = PropertiesList(
    Property("reporting_category", StringType),
    Property("currency", StringType),
    Property("count", IntegerType),
    Property("gross", NumberType),
    Property("fee", NumberType),
    Property("net", NumberType),
    Property("interval_end_at", IntegerType),
    Property("loaded_at", DateTimeType),
).to_dict()


balance_change_from_activity_itemized_2_schema = PropertiesList(
    Property("balance_transaction_id", StringType),
    Property("created_utc", DateTimeType),
    Property("available_on_utc", DateTimeType),
    Property("currency", StringType),
    Property("gross", NumberType),
    Property("fee", NumberType),
    Property("net", NumberType),
    Property("reporting_category", StringType),
    Property("source_id", StringType),
    Property("description", StringType),
    Property("customer_facing_amount", StringType),
    Property("customer_facing_currency", StringType),
    Property("regulatory_tag", StringType),
    Property("automatic_payout_id", StringType),
    Property("automatic_payout_effective_at", DateTimeType),
    Property("customer_id", StringType),
    Property("customer_email", StringType),
    Property("customer_description", StringType),
    Property("customer_shipping_address_line1", StringType),
    Property("customer_shipping_address_line2", StringType),
    Property("customer_shipping_address_city", StringType),
    Property("customer_shipping_address_state", StringType),
    Property("customer_shipping_address_postal_code", StringType),
    Property("customer_shipping_address_country", StringType),
    Property("customer_address_line1", StringType),
    Property("customer_address_line2", StringType),
    Property("customer_address_city", StringType),
    Property("customer_address_state", StringType),
    Property("customer_address_postal_code", StringType),
    Property("customer_address_country", StringType),
    Property("shipping_address_line1", StringType),
    Property("shipping_address_line2", StringType),
    Property("shipping_address_city", StringType),
    Property("shipping_address_state", StringType),
    Property("shipping_address_postal_code", StringType),
    Property("shipping_address_country", StringType),
    Property("card_address_line1", StringType),
    Property("card_address_line2", StringType),
    Property("card_address_city", StringType),
    Property("card_address_state", StringType),
    Property("card_address_postal_code", StringType),
    Property("card_address_country", StringType),
    Property("charge_id", StringType),
    Property("payment_intent_id", StringType),
    Property("charge_created_utc", DateTimeType),
    Property("invoice_id", StringType),
    Property("invoice_number", StringType),
    Property("subscription_id", StringType),
    Property("payment_method_type", StringType),
    Property("is_link", BooleanType),
    Property("card_brand", StringType),
    Property("card_funding", StringType),
    Property("card_country", IntegerType),
    Property("statement_descriptor", StringType),
    Property("dispute_reason", StringType),
    Property("connected_account_id", StringType),
    Property("connected_account_name", StringType),
    Property("connected_account_country", StringType),
    Property("connected_account_direct_charge_id", StringType),
    Property("interval_end_at", IntegerType),
    Property("loaded_at", DateTimeType),
).to_dict()


balance_change_from_activity_summary_1_schema = PropertiesList(
    Property("reporting_category", StringType),
    Property("currency", StringType),
    Property("count", IntegerType),
    Property("gross", NumberType),
    Property("fee", NumberType),
    Property("net", NumberType),
    Property("interval_end_at", IntegerType),
    Property("loaded_at", DateTimeType),
).to_dict()
